version: "3"
services:
  mysqldb:
    image: mysql
    container_name: mysql_prod
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: maminizer/repo:latest
    container_name: achat
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" 
        }'
    volumes:
      - .m2:/root/.m2

     
  angular_front:
    image: anas1412/achatfront
    container_name: achatangular
    restart: on-failure
    ports:
     - 4200:80
    depends_on:
     - backend
     
volumes:
  db:
     
