version: "3"
volumes:
  mysql-data:
    driver: local
services:
   mysqldb:
    image: mysql:8.0
    container_name: mysql_prod
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb


  backend:
    image: maminizer/repo:latest
    container_name: maminizer
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     - 8089:8089
    depends_on:
     - mysqldb
     
  angular_front:
    image: anas1412/achatfront
    container_name: achatangular
    restart: on-failure
    ports:
     - 4200:80
    depends_on:
     - backend
     
     
