version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
     
     - MYSQL_DATABASE=achatdb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root


  spring_app:
    image: maminizer/repo:14
    container_name: maminizer
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
